import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from "docx";
import jsPDF from "jspdf";
import pptxgen from "pptxgenjs";
import "./fonts/NotoSans-normal.js";
import "./fonts/NotoSans-bold.js";
import "./fonts/NotoSans-italic.js";

// Clean markdown artifacts from text
export const cleanText = (text: string) => {
  return text
    .replace(/\*\*/g, "")
    .replace(/##\s/g, "")
    .replace(/^-\s/gm, "")
    .replace(/^›\s/gm, "")
    .trim();
};

// Parse analysis into sections
const parseSections = (analysis: string) => {
  const lines = analysis.split("\n").filter((l) => l.trim() !== "");
  const sections: { title: string; content: string[] }[] = [];
  let current: { title: string; content: string[] } | null = null;

  for (const line of lines) {
    const clean = cleanText(line);
    if (!clean) continue;

    const isHeader =
      line.startsWith("## ") ||
      line.startsWith("# ") ||
      (line === line.toUpperCase() && line.length > 3 && line.length < 60) ||
      ["EXECUTIVE SUMMARY", "KEY FINDINGS", "AREAS OF CONCERN",
       "OPPORTUNITIES", "RECOMMENDED WATCH AREAS", "FORWARD-LOOKING STATEMENTS",
       "Executive Summary", "Key Findings", "Areas of Concern",
       "Opportunities", "Recommended Watch Areas"].some(h => clean.startsWith(h));

    if (isHeader) {
      if (current) sections.push(current);
      current = { title: clean.replace(/^#+\s/, ""), content: [] };
    } else if (current) {
      current.content.push(clean);
    } else {
      current = { title: "", content: [clean] };
    }
  }
  if (current) sections.push(current);
  return sections;
};

// ── WORD DOWNLOAD ──────────────────────────────────────────────────────────
export const downloadWord = async (
  analysis: string,
  audience: string,
  format: string
) => {
  const sections = parseSections(analysis);

  const children: Paragraph[] = [
    new Paragraph({
      children: [new TextRun({ text: "DashboardIntel", bold: true, size: 28, color: "C9A84C" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `${audience} · ${format}`, size: 20, color: "9C8A6E" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "E8E0D0" } },
    }),
  ];

  for (const section of sections) {
    if (section.content.length === 0) continue;
    if (section.title) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: section.title.toUpperCase(), bold: true, size: 22, color: "C9A84C" })],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 480, after: 240 },
        })
      );
    }
    for (const line of section.content) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 22, color: "2C2C2C" })],
          spacing: { after: 200, line: 340 },
          alignment: AlignmentType.JUSTIFIED,
          indent: section.title ? { left: 200 } : undefined,
        })
      );
    }
  }

  children.push(
    new Paragraph({
      children: [new TextRun({ text: "Generated by DashboardIntel · For internal use only", size: 16, color: "9C8A6E", italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    })
  );

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.docx`;
  a.click();
  URL.revokeObjectURL(url);
};

// ── PDF DOWNLOAD ───────────────────────────────────────────────────────────
export const downloadPDF = (
  analysis: string,
  audience: string,
  format: string
) => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  doc.setFont("NotoSans-Regular", "normal");
  const sections = parseSections(analysis);
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 22;
  const maxW = pageW - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > 270) { doc.addPage(); y = 20; }
  };

  // Header
  doc.setFontSize(18);
  doc.setTextColor(201, 168, 76);
  doc.text("DashboardIntel", pageW / 2, y, { align: "center" });
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(156, 138, 110);
  doc.text(`${audience} · ${format}`, pageW / 2, y, { align: "center" });
  y += 6;

  doc.setDrawColor(201, 168, 76);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 10;

  for (const section of sections) {
    if (section.content.length === 0) continue;
    if (section.title) {
      checkPage(14);
      doc.setFontSize(11);
      doc.setTextColor(201, 168, 76);
      doc.setFont("NotoSans-Bold", "bold");
      doc.text(section.title.toUpperCase(), margin, y);
      y += 7;
    }

    doc.setFont("NotoSans-Regular", "normal");
    doc.setFontSize(10);
    doc.setTextColor(44, 44, 44);

    for (const line of section.content) {
      const lineWidth = maxW - (section.title ? 5 : 0);
      const wrapped = doc.splitTextToSize(line, lineWidth);
      checkPage(wrapped.length * 5 + 3);
      doc.text(wrapped, section.title ? margin + 5 : margin, y);
      y += wrapped.length * 5 + 3;
    }
    y += 3;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(156, 138, 110);
  doc.setFont("NotoSans-Italic", "italic");
  doc.text("Generated by DashboardIntel · For internal use only · Not financial or legal advice",
    pageW / 2, 285, { align: "center" });

  doc.save(`DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.pdf`);
};

// ── POWERPOINT DOWNLOAD ────────────────────────────────────────────────────
export const downloadPPT = (
  analysis: string,
  audience: string,
  format: string
) => {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  const sections = parseSections(analysis);

  const BG = "0E0B08";
  const PANEL = "1A1410";
  const GOLD = "C9A84C";
  const GOLD_DIM = "8A7434";
  const MUTED = "9C8A6E";
  const WHITE = "F5EDE0";

  // ── TITLE SLIDE ─────────────────────────────────────────────────────────
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: BG };

  // Left gold accent bar (full height)
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.15, h: 7.5,
    fill: { color: GOLD }, line: { color: GOLD },
  });

  // Small wordmark top-left
  titleSlide.addText("DASHBOARDINTEL", {
    x: 0.6, y: 0.5, w: 6, h: 0.3,
    fontSize: 10, bold: true, color: GOLD, charSpacing: 6,
  });

  // Big title — centered vertically
  titleSlide.addText("Dashboard\nIntelligence Report", {
    x: 0.6, y: 2.6, w: 12, h: 1.8,
    fontSize: 48, bold: true, color: WHITE,
    fontFace: "Georgia", lineSpacingMultiple: 1.05,
  });

  // Audience/format line
  titleSlide.addText(`${audience}  ·  ${format}`, {
    x: 0.6, y: 4.5, w: 12, h: 0.4,
    fontSize: 14, color: GOLD, charSpacing: 2,
  });

  // Hairline rule
  titleSlide.addShape(pptx.ShapeType.line, {
    x: 0.6, y: 5.05, w: 1.2, h: 0,
    line: { color: GOLD_DIM, width: 1 },
  });

  // Tagline
  titleSlide.addText("Every number has a story.", {
    x: 0.6, y: 5.2, w: 12, h: 0.4,
    fontSize: 13, color: MUTED, italic: true,
  });

  // Date bottom-right
  titleSlide.addText(new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric"
  }), {
    x: 9, y: 7.0, w: 3.8, h: 0.3,
    fontSize: 9, color: MUTED, align: "right", charSpacing: 1,
  });

  // ── CONTENT SLIDES ──────────────────────────────────────────────────────
  const titledSections = sections.filter(
    s => s.title && s.content.length > 0 && s.content.join(" ").length >= 100
  );
  let sectionIndex = 0;

  for (const section of titledSections) {
    sectionIndex++;
    const slide = pptx.addSlide();
    slide.background = { color: BG };

    // LEFT PANEL — dark with section meta
    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: 3.8, h: 7.5,
      fill: { color: PANEL }, line: { color: PANEL },
    });

    // Thin gold left edge on the panel
    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: 0.08, h: 7.5,
      fill: { color: GOLD }, line: { color: GOLD },
    });

    // Section number — large, serif
    slide.addText(String(sectionIndex).padStart(2, "0"), {
      x: 0.5, y: 2.5, w: 3, h: 1.6,
      fontSize: 80, color: GOLD, fontFace: "Georgia",
    });

    // Thin rule under number
    slide.addShape(pptx.ShapeType.line, {
      x: 0.55, y: 4.3, w: 0.8, h: 0,
      line: { color: GOLD_DIM, width: 1 },
    });

    // Section title — stacked, tracked-out
    slide.addText(section.title.toUpperCase(), {
      x: 0.55, y: 4.5, w: 3, h: 1.8,
      fontSize: 14, bold: true, color: WHITE,
      charSpacing: 4, lineSpacingMultiple: 1.3,
    });

    // RIGHT CONTENT AREA
    // Content — native bullets give proper hanging indent + autoFit handles overflow
    if (section.content.length > 1) {
      const items = section.content.map(line => ({
        text: line,
        options: {
          bullet: { code: "25B8", indent: 25 },
          paraSpaceAfter: 14,
          color: WHITE,
        },
      }));
      slide.addText(items, {
        x: 4.2, y: 0.8, w: 8.8, h: 5.8,
        fontSize: 13,
        valign: "top", wrap: true,
        align: "left",
        lineSpacingMultiple: 1.4,
        autoFit: true,
      });
    } else {
      slide.addText(section.content[0], {
        x: 4.2, y: 0.8, w: 8.8, h: 5.8,
        fontSize: 14, color: WHITE,
        valign: "top", wrap: true,
        align: "left",
        lineSpacingMultiple: 1.55,
        autoFit: true,
      });
    }

    // Footer wordmark — right side only (no page count)
    slide.addText("DashboardIntel", {
      x: 4.2, y: 7.1, w: 8.8, h: 0.3,
      fontSize: 8, color: MUTED, align: "right", charSpacing: 2,
    });
  }

  // ── CLOSING SLIDE ───────────────────────────────────────────────────────
  const closingSlide = pptx.addSlide();
  closingSlide.background = { color: BG };

  closingSlide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.15, h: 7.5,
    fill: { color: GOLD }, line: { color: GOLD },
  });

  closingSlide.addText("End of report.", {
    x: 0.6, y: 3.0, w: 12, h: 1.0,
    fontSize: 36, color: WHITE, fontFace: "Georgia", italic: true,
  });

  closingSlide.addShape(pptx.ShapeType.line, {
    x: 0.6, y: 4.1, w: 1.2, h: 0,
    line: { color: GOLD_DIM, width: 1 },
  });

  closingSlide.addText("Generated by DashboardIntel  ·  For internal use only", {
    x: 0.6, y: 4.3, w: 12, h: 0.4,
    fontSize: 11, color: MUTED, charSpacing: 1,
  });

  pptx.writeFile({ fileName: `DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.pptx` });
};