import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from "docx";
import jsPDF from "jspdf";
import pptxgen from "pptxgenjs";
import "./fonts/NotoSans-normal.js";
import "./fonts/NotoSans-bold.js";
import "./fonts/NotoSans-italic.js";

// ── TYPES ──────────────────────────────────────────────────────────────────
type ContentItem =
  | { type: "prose"; text: string }
  | { type: "bullet"; text: string };

type Section = {
  title: string;
  content: ContentItem[];
};

// ── PARSER ─────────────────────────────────────────────────────────────────
const parseSections = (analysis: string): Section[] => {
  const sections: Section[] = [];
  let current: Section | null = null;
  let proseBuffer: string[] = [];

  const flushProse = () => {
    if (proseBuffer.length > 0 && current) {
      current.content.push({
        type: "prose",
        text: proseBuffer.join(" ").trim(),
      });
      proseBuffer = [];
    }
  };

  for (const rawLine of analysis.split("\n")) {
    const line = rawLine.trim();

    if (!line) {
      flushProse();
      continue;
    }

    if (line.startsWith("## ")) {
      flushProse();
      if (current) sections.push(current);
      current = {
        title: line.replace(/^##\s+/, "").replace(/\*\*/g, "").trim(),
        content: [],
      };
      continue;
    }

    if (/^[-•▸]\s+/.test(line)) {
      flushProse();
      if (!current) current = { title: "", content: [] };
      current.content.push({
        type: "bullet",
        text: line.replace(/^[-•▸]\s+/, "").replace(/\*\*/g, "").trim(),
      });
      continue;
    }

    if (current) {
      proseBuffer.push(line.replace(/\*\*/g, ""));
    }
  }

  flushProse();
  if (current) sections.push(current);

  // Fallback: if no sections detected, wrap entire output as ANALYSIS
  if (sections.length === 0 && analysis.trim()) {
    sections.push({
      title: "ANALYSIS",
      content: [{ type: "prose", text: analysis.replace(/\*\*/g, "").trim() }],
    });
  }

  return sections;
};

// ── DISPLAY HELPER (for frontend) ──────────────────────────────────────────
export const cleanForDisplay = (analysis: string): string =>
  analysis
    .replace(/^##\s+/gm, "")
    .replace(/^[-•]\s+/gm, "•  ")
    .replace(/\*\*/g, "")
    .trim();

// ── WORD DOWNLOAD ──────────────────────────────────────────────────────────
export const downloadWord = async (
  analysis: string,
  audience: string,
  format: string
) => {
  const sections = parseSections(analysis);

  const children: Paragraph[] = [
    new Paragraph({
      children: [new TextRun({ text: "DashboardIntel", bold: true, size: 28, color: "C9A84C" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `${audience} · ${format}`, size: 20, color: "9C8A6E" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "E8E0D0" } },
    }),
  ];

  for (const section of sections) {
    if (section.content.length === 0) continue;

    if (section.title) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: section.title.toUpperCase(), bold: true, size: 22, color: "C9A84C" })],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 480, after: 240 },
        })
      );
    }

    for (const item of section.content) {
      if (item.type === "bullet") {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: item.text, size: 22, color: "2C2C2C" })],
            bullet: { level: 0 },
            spacing: { after: 160, line: 320 },
          })
        );
      } else {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: item.text, size: 22, color: "2C2C2C" })],
            spacing: { after: 200, line: 340 },
            alignment: AlignmentType.JUSTIFIED,
            indent: section.title ? { left: 200 } : undefined,
          })
        );
      }
    }
  }

  children.push(
    new Paragraph({
      children: [new TextRun({ text: "Generated by DashboardIntel · For internal use only", size: 16, color: "9C8A6E", italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    })
  );

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.docx`;
  a.click();
  URL.revokeObjectURL(url);
};

// ── PDF DOWNLOAD ───────────────────────────────────────────────────────────
export const downloadPDF = (
  analysis: string,
  audience: string,
  format: string
) => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  doc.setFont("NotoSans-Regular", "normal");
  const sections = parseSections(analysis);
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 22;
  const maxW = pageW - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > 270) { doc.addPage(); y = 20; }
  };

  // Header
  doc.setFontSize(18);
  doc.setTextColor(201, 168, 76);
  doc.text("DashboardIntel", pageW / 2, y, { align: "center" });
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(156, 138, 110);
  doc.text(`${audience} · ${format}`, pageW / 2, y, { align: "center" });
  y += 6;

  doc.setDrawColor(201, 168, 76);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 10;

  for (const section of sections) {
    if (section.content.length === 0) continue;

    if (section.title) {
      checkPage(14);
      doc.setFontSize(11);
      doc.setTextColor(201, 168, 76);
      doc.setFont("NotoSans-Bold", "bold");
      doc.text(section.title.toUpperCase(), margin, y);
      y += 7;
    }

    doc.setFont("NotoSans-Regular", "normal");
    doc.setFontSize(10);
    doc.setTextColor(44, 44, 44);

    for (const item of section.content) {
      if (item.type === "bullet") {
        const bulletIndent = 6;
        const textWidth = maxW - bulletIndent - (section.title ? 5 : 0);
        const wrapped = doc.splitTextToSize(item.text, textWidth);
        const lineHeight = 5.8;
        checkPage(wrapped.length * lineHeight + 5);
        doc.setTextColor(201, 168, 76);
        doc.text("▸", margin + (section.title ? 5 : 0), y);
        doc.setTextColor(44, 44, 44);
        doc.text(wrapped, margin + bulletIndent + (section.title ? 5 : 0), y, {
          lineHeightFactor: 1.5,
        });
        y += wrapped.length * lineHeight + 5;
      } else {
        const lineWidth = maxW - (section.title ? 5 : 0);
        const wrapped = doc.splitTextToSize(item.text, lineWidth);
        const lineHeight = 5.8;
        checkPage(wrapped.length * lineHeight + 6);
        doc.text(wrapped, section.title ? margin + 5 : margin, y, {
          lineHeightFactor: 1.5,
        });
        y += wrapped.length * lineHeight + 6;
      }
    }
    y += 6;
  }

  // Footer on every page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 138, 110);
    doc.setFont("NotoSans-Italic", "italic");
    doc.text("Generated by DashboardIntel · For internal use only · Not financial or legal advice",
      pageW / 2, 285, { align: "center" });
  }

  doc.save(`DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.pdf`);
};

// ── POWERPOINT DOWNLOAD ────────────────────────────────────────────────────
export const downloadPPT = (
  analysis: string,
  audience: string,
  format: string
) => {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  const sections = parseSections(analysis);

  const BG = "0E0B08";
  const GOLD = "C9A84C";
  const GOLD_DEEP = "8A7434";
  const PANEL_TEXT = "1A1410";
  const MUTED = "9C8A6E";
  const WHITE = "F5EDE0";

  const f = format.toLowerCase();
  const isOnePageBrief = f.includes("one-page") || f.includes("one page");
  const isStructured = f.includes("structured") || f.includes("narrative");

  // ── TITLE SLIDE ─────────────────────────────────────────────────────────
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: BG };

  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.15, h: 7.5,
    fill: { color: GOLD }, line: { color: GOLD },
  });

  titleSlide.addText("DASHBOARDINTEL", {
    x: 0.6, y: 0.5, w: 6, h: 0.3,
    fontSize: 10, bold: true, color: GOLD, charSpacing: 6,
  });

  titleSlide.addText("Dashboard\nIntelligence Report", {
    x: 0.6, y: 2.6, w: 12, h: 1.8,
    fontSize: 48, bold: true, color: WHITE,
    fontFace: "Georgia", lineSpacingMultiple: 1.05,
  });

  titleSlide.addText(`${audience}  ·  ${format}`, {
    x: 0.6, y: 4.5, w: 12, h: 0.4,
    fontSize: 14, color: GOLD, charSpacing: 2,
  });

  titleSlide.addShape(pptx.ShapeType.line, {
    x: 0.6, y: 5.05, w: 1.2, h: 0,
    line: { color: GOLD_DEEP, width: 1 },
  });

  titleSlide.addText("Every number has a story.", {
    x: 0.6, y: 5.2, w: 12, h: 0.4,
    fontSize: 13, color: MUTED, italic: true,
  });

  titleSlide.addText(new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric"
  }), {
    x: 9, y: 7.0, w: 3.8, h: 0.3,
    fontSize: 9, color: MUTED, align: "right", charSpacing: 1,
  });

  // ── CONTENT SLIDES ──────────────────────────────────────────────────────
if (isOnePageBrief) {
    const findings = sections.find(s => s.title.toUpperCase().includes("FINDING"));
    const recs = sections.find(s =>
      s.title.toUpperCase().includes("RECOMMEND") || s.title.toUpperCase().includes("ACTION")
    );

    const briefSlides: { label: string; section: typeof findings }[] = [];
    if (findings) briefSlides.push({ label: "KEY FINDINGS", section: findings });
    if (recs) briefSlides.push({ label: "RECOMMENDATIONS", section: recs });

    briefSlides.forEach(({ label, section }, idx) => {
      if (!section) return;
      const slide = pptx.addSlide();
      slide.background = { color: BG };

      // Gold left panel
      slide.addShape(pptx.ShapeType.rect, {
        x: 0, y: 0, w: 3.8, h: 7.5,
        fill: { color: GOLD }, line: { color: GOLD },
      });

      // Section number
      slide.addText(String(idx + 1).padStart(2, "0"), {
        x: 0.5, y: 2.5, w: 3, h: 1.6,
        fontSize: 80, color: PANEL_TEXT, fontFace: "Georgia",
      });

      slide.addShape(pptx.ShapeType.line, {
        x: 0.55, y: 4.3, w: 0.8, h: 0,
        line: { color: PANEL_TEXT, width: 1 },
      });

      // Panel title
      slide.addText(label, {
        x: 0.55, y: 4.5, w: 3, h: 1.0,
        fontSize: 14, bold: true, color: PANEL_TEXT,
        charSpacing: 4, lineSpacingMultiple: 1.3,
      });

      // Right-side title
      slide.addText(label, {
        x: 4.2, y: 0.5, w: 8.8, h: 0.4,
        fontSize: 13, bold: true, color: GOLD, charSpacing: 6,
      });

      // Bullets
      const bulletText = section.content
        .filter(i => i.type === "bullet")
        .map(i => i.text).join("\n");

      slide.addText(bulletText, {
        x: 4.2, y: 1.2, w: 8.8, h: 5.6,
        fontSize: 13, color: WHITE,
        valign: "top", wrap: true,
        bullet: { code: "25B8", indent: 22 },
        paraSpaceAfter: 12,
        lineSpacingMultiple: 1.45,
        autoFit: true,
      });

      // Footer
      slide.addText("DashboardIntel", {
        x: 4.2, y: 7.1, w: 8.8, h: 0.3,
        fontSize: 8, color: MUTED, align: "right", charSpacing: 2,
      });
    });

    // Closing slide for One-Page Brief
    const closing = pptx.addSlide();
    closing.background = { color: BG };

    closing.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: 0.15, h: 7.5,
      fill: { color: GOLD }, line: { color: GOLD },
    });

    closing.addText("Thank you.", {
      x: 0.6, y: 3.0, w: 12, h: 1.0,
      fontSize: 36, color: WHITE, fontFace: "Georgia", italic: true,
    });

    closing.addShape(pptx.ShapeType.line, {
      x: 0.6, y: 4.1, w: 1.2, h: 0,
      line: { color: GOLD_DEEP, width: 1 },
    });

    closing.addText("Generated by DashboardIntel  ·  For internal use only", {
      x: 0.6, y: 4.3, w: 12, h: 0.4,
      fontSize: 11, color: MUTED, charSpacing: 1,
    });
  } else {
    // STRUCTURED NARRATIVE or BULLET HIGHLIGHTS: one slide per section
    const renderable = sections.filter(s => s.title && s.content.length > 0);

    renderable.forEach((section, idx) => {
      const slide = pptx.addSlide();
      slide.background = { color: BG };

      slide.addShape(pptx.ShapeType.rect, {
        x: 0, y: 0, w: 3.8, h: 7.5,
        fill: { color: GOLD }, line: { color: GOLD },
      });

      slide.addText(String(idx + 1).padStart(2, "0"), {
        x: 0.5, y: 2.5, w: 3, h: 1.6,
        fontSize: 80, color: PANEL_TEXT, fontFace: "Georgia",
      });

      slide.addShape(pptx.ShapeType.line, {
        x: 0.55, y: 4.3, w: 0.8, h: 0,
        line: { color: PANEL_TEXT, width: 1 },
      });

      slide.addText(section.title.toUpperCase(), {
        x: 0.55, y: 4.5, w: 3, h: 1.8,
        fontSize: 14, bold: true, color: PANEL_TEXT,
        charSpacing: 4, lineSpacingMultiple: 1.3,
      });

      slide.addText(section.title.toUpperCase(), {
        x: 4.2, y: 0.5, w: 8.8, h: 0.4,
        fontSize: 13, bold: true, color: GOLD, charSpacing: 6,
      });

      const bullets = section.content.filter(i => i.type === "bullet");
      const prose = section.content.filter(i => i.type === "prose");

      if (bullets.length > 0 && prose.length === 0) {
        const bulletText = bullets.map(b => b.text).join("\n");
        slide.addText(bulletText, {
          x: 4.2, y: 1.2, w: 8.8, h: 5.6,
          fontSize: 13, color: WHITE,
          valign: "top", wrap: true,
          bullet: { code: "25B8", indent: 22 },
          paraSpaceAfter: 12,
          lineSpacingMultiple: 1.4,
          autoFit: true,
        });
      } else if (prose.length > 0 && bullets.length === 0) {
        const proseText = prose.map(p => p.text).join("\n\n");
        slide.addText(proseText, {
          x: 4.2, y: 1.2, w: 8.8, h: 5.6,
          fontSize: 13, color: WHITE,
          valign: "top", wrap: true,
          paraSpaceAfter: 14,
          lineSpacingMultiple: 1.5,
          autoFit: true,
        });
      } else {
        const proseText = prose.map(p => p.text).join("\n\n");
        slide.addText(proseText, {
          x: 4.2, y: 1.2, w: 8.8, h: 3.0,
          fontSize: 12, color: WHITE,
          valign: "top", wrap: true,
          paraSpaceAfter: 10,
          lineSpacingMultiple: 1.4,
          autoFit: true,
        });
        const bulletText = bullets.map(b => b.text).join("\n");
        slide.addText(bulletText, {
          x: 4.2, y: 4.3, w: 8.8, h: 2.5,
          fontSize: 12, color: WHITE,
          valign: "top", wrap: true,
          bullet: { code: "25B8", indent: 22 },
          paraSpaceAfter: 8,
          lineSpacingMultiple: 1.4,
          autoFit: true,
        });
      }

      slide.addText("DashboardIntel", {
        x: 4.2, y: 7.1, w: 8.8, h: 0.3,
        fontSize: 8, color: MUTED, align: "right", charSpacing: 2,
      });
    });

    // Closing slide for Structured Narrative only
    if (isStructured) {
      const closing = pptx.addSlide();
      closing.background = { color: BG };

      closing.addShape(pptx.ShapeType.rect, {
        x: 0, y: 0, w: 0.15, h: 7.5,
        fill: { color: GOLD }, line: { color: GOLD },
      });

      closing.addText("End of report.", {
        x: 0.6, y: 3.0, w: 12, h: 1.0,
        fontSize: 36, color: WHITE, fontFace: "Georgia", italic: true,
      });

      closing.addShape(pptx.ShapeType.line, {
        x: 0.6, y: 4.1, w: 1.2, h: 0,
        line: { color: GOLD_DEEP, width: 1 },
      });

      closing.addText("Generated by DashboardIntel  ·  For internal use only", {
        x: 0.6, y: 4.3, w: 12, h: 0.4,
        fontSize: 11, color: MUTED, charSpacing: 1,
      });
    }
  }

  pptx.writeFile({ fileName: `DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.pptx` });
};