import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from "docx";
import jsPDF from "jspdf";
import pptxgen from "pptxgenjs";
import "./fonts/NotoSans-normal.js";
import "./fonts/NotoSans-bold.js";
import "./fonts/NotoSans-italic.js";

// Clean markdown artifacts from text
export const cleanText = (text: string) => {
  return text
    .replace(/\*\*/g, "")
    .replace(/##\s/g, "")
    .replace(/^-\s/gm, "")
    .replace(/^›\s/gm, "")
    .trim();
};

// Parse analysis into sections
const parseSections = (analysis: string) => {
  const lines = analysis.split("\n").filter((l) => l.trim() !== "");
  const sections: { title: string; content: string[] }[] = [];
  let current: { title: string; content: string[] } | null = null;

  for (const line of lines) {
    const clean = cleanText(line);
    if (!clean) continue;

    const isHeader =
      line.startsWith("## ") ||
      line.startsWith("# ") ||
      (line === line.toUpperCase() && line.length > 3 && line.length < 60) ||
      ["EXECUTIVE SUMMARY", "KEY FINDINGS", "AREAS OF CONCERN",
       "OPPORTUNITIES", "RECOMMENDED WATCH AREAS", "FORWARD-LOOKING STATEMENTS",
       "Executive Summary", "Key Findings", "Areas of Concern",
       "Opportunities", "Recommended Watch Areas"].some(h => clean.startsWith(h));

    if (isHeader) {
      if (current) sections.push(current);
      current = { title: clean.replace(/^#+\s/, ""), content: [] };
    } else if (current) {
      current.content.push(clean);
    } else {
      current = { title: "", content: [clean] };
    }
  }
  if (current) sections.push(current);
  return sections;
};

// ── WORD DOWNLOAD ──────────────────────────────────────────────────────────
export const downloadWord = async (
  analysis: string,
  audience: string,
  format: string
) => {
  const sections = parseSections(analysis);

  const children: Paragraph[] = [
    new Paragraph({
      children: [new TextRun({ text: "DashboardIntel", bold: true, size: 28, color: "C9A84C" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `${audience} · ${format}`, size: 20, color: "9C8A6E" })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "E8E0D0" } },
    }),
  ];

  for (const section of sections) {
    if (section.content.length === 0) continue;
    if (section.title) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: section.title.toUpperCase(), bold: true, size: 22, color: "C9A84C" })],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 480, after: 240 },
        })
      );
    }
    for (const line of section.content) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 22, color: "2C2C2C" })],
          spacing: { after: 200, line: 340 },
          alignment: AlignmentType.JUSTIFIED,
          indent: section.title ? { left: 200 } : undefined,
        })
      );
    }
  }

  children.push(
    new Paragraph({
      children: [new TextRun({ text: "Generated by DashboardIntel · For internal use only", size: 16, color: "9C8A6E", italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    })
  );

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.docx`;
  a.click();
  URL.revokeObjectURL(url);
};

// ── PDF DOWNLOAD ───────────────────────────────────────────────────────────
export const downloadPDF = (
  analysis: string,
  audience: string,
  format: string
) => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  doc.setFont("NotoSans-Regular", "normal");
  const sections = parseSections(analysis);
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 22;
  const maxW = pageW - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > 270) { doc.addPage(); y = 20; }
  };

  // Header
  doc.setFontSize(18);
  doc.setTextColor(201, 168, 76);
  doc.text("DashboardIntel", pageW / 2, y, { align: "center" });
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(156, 138, 110);
  doc.text(`${audience} · ${format}`, pageW / 2, y, { align: "center" });
  y += 6;

  doc.setDrawColor(201, 168, 76);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 10;

  for (const section of sections) {
    if (section.content.length === 0) continue;
    if (section.title) {
      checkPage(14);
      doc.setFontSize(11);
      doc.setTextColor(201, 168, 76);
      doc.setFont("NotoSans-Bold", "bold");
      doc.text(section.title.toUpperCase(), margin, y);
      y += 7;
    }

    doc.setFont("NotoSans-Regular", "normal");
    doc.setFontSize(10);
    doc.setTextColor(44, 44, 44);

    for (const line of section.content) {
      const lineWidth = maxW - (section.title ? 5 : 0);
      const wrapped = doc.splitTextToSize(line, lineWidth);
      checkPage(wrapped.length * 5.5 + 4);
      doc.text(wrapped, section.title ? margin + 5 : margin, y, {
        align: "justify",
        maxWidth: lineWidth,
      });
      y += wrapped.length * 5.5 + 5;
    }
    y += 5;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(156, 138, 110);
  doc.setFont("NotoSans-Italic", "italic");
  doc.text("Generated by DashboardIntel · For internal use only · Not financial or legal advice",
    pageW / 2, 285, { align: "center" });

  doc.save(`DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.pdf`);
};

// ── POWERPOINT DOWNLOAD ────────────────────────────────────────────────────
export const downloadPPT = (
  analysis: string,
  audience: string,
  format: string
) => {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  const sections = parseSections(analysis);

  const BG = "0E0B08";
  const GOLD = "C9A84C";
  const MUTED = "9C8A6E";
  const WHITE = "F5EDE0";

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: BG };
  titleSlide.addText("DashboardIntel", {
    x: 1, y: 1.5, w: 11, h: 1.2,
    fontSize: 40, bold: true, color: GOLD, align: "center",
  });
  titleSlide.addText(`${audience} · ${format}`, {
    x: 1, y: 2.8, w: 11, h: 0.6,
    fontSize: 18, color: MUTED, align: "center",
  });
  titleSlide.addShape(pptx.ShapeType.line, {
    x: 2, y: 3.6, w: 9, h: 0,
    line: { color: GOLD, width: 0.5 },
  });
  titleSlide.addText("Every number has a story.", {
    x: 1, y: 4, w: 11, h: 0.6,
    fontSize: 14, color: MUTED, align: "center", italic: true,
  });

  // Content slides — one per section
  const titledSections = sections.filter(s => s.content.length > 0 && s.title);
  const totalSlides = titledSections.length + 1;
  let sectionIndex = 0;

  for (const section of titledSections) {
    sectionIndex++;
    const slide = pptx.addSlide();
    slide.background = { color: BG };

    // Hairline gold rule at top
    slide.addShape(pptx.ShapeType.line, {
      x: 0.5, y: 0.5, w: 0.6, h: 0,
      line: { color: GOLD, width: 1.5 },
    });

    // Large section number
    slide.addText(String(sectionIndex).padStart(2, "0"), {
      x: 11.3, y: 0.3, w: 1.5, h: 0.8,
      fontSize: 36, color: GOLD, align: "right",
      fontFace: "Georgia",
    });

    // Section title — small, tracked-out, label style
    slide.addText(section.title.toUpperCase(), {
      x: 0.5, y: 0.7, w: 10, h: 0.5,
      fontSize: 11, bold: true, color: GOLD,
      charSpacing: 4,
    });

    // Content
    const contentText = section.content.join("\n\n");
    slide.addText(contentText, {
      x: 0.7,
      y: 1.6,
      w: 11.5,
      h: 5.0,
      fontSize: 14,
      color: WHITE,
      valign: "top",
      wrap: true,
      paraSpaceAfter: 12,
      lineSpacingMultiple: 1.45,
    });

    // Footer with page count
    slide.addText("DashboardIntel · For internal use only", {
      x: 0.5, y: 7.1, w: 10, h: 0.3,
      fontSize: 8, color: MUTED, align: "left",
    });
    slide.addText(`${sectionIndex + 1} / ${totalSlides}`, {
      x: 11.3, y: 7.1, w: 1.5, h: 0.3,
      fontSize: 8, color: MUTED, align: "right",
    });
  }

  pptx.writeFile({ fileName: `DashboardIntel_${audience.replace(/\//g, "-")}_${format.replace(/\s/g, "_")}.pptx` });
};