"use client";

interface AnalysisResultProps {
  analysis: string;
  audience: string;
  format: string;
  onReset: () => void;
}

export default function AnalysisResult({
  analysis,
  audience,
  format,
  onReset,
}: AnalysisResultProps) {
  const handleCopy = () => {
    navigator.clipboard.writeText(analysis);
  };

  const formatAnalysis = (text: string) => {
    const lines = text.split("\n");
    return lines.map((line, i) => {
      if (line.startsWith("## ")) {
        return (
          <h2 key={i} className="text-blue-400 text-xs font-medium tracking-widest uppercase mt-8 mb-3">
            {line.replace("## ", "")}
          </h2>
        );
      }
      if (line.startsWith("# ")) {
        return (
          <h1 key={i} className="text-white text-lg font-medium mt-6 mb-3">
            {line.replace("# ", "")}
          </h1>
        );
      }
      if (line.startsWith("**") && line.endsWith("**")) {
        return (
          <p key={i} className="text-white font-medium text-sm mt-4 mb-1">
            {line.replace(/\*\*/g, "")}
          </p>
        );
      }
      if (line.startsWith("- ") || line.startsWith("• ")) {
        return (
          <div key={i} className="flex gap-3 my-2">
            <span className="text-blue-500 mt-1 shrink-0">›</span>
            <p className="text-slate-300 text-sm leading-relaxed">
              {line.replace(/^[-•]\s/, "")}
            </p>
          </div>
        );
      }
      if (line.trim() === "") {
        return <div key={i} className="h-2" />;
      }
      return (
        <p key={i} className="text-slate-300 text-sm leading-relaxed my-1">
          {line}
        </p>
      );
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between pb-4 border-b border-slate-800">
        <div>
          <p className="text-xs font-medium tracking-widest text-slate-500 uppercase">
            Analysis ready
          </p>
          <p className="text-slate-400 text-sm mt-1">
            {audience} · {format}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-lg border border-slate-700 text-slate-400 text-xs font-medium hover:border-slate-500 hover:text-slate-300 transition-all"
          >
            Copy
          </button>
          <button
            onClick={onReset}
            className="px-4 py-2 rounded-lg border border-slate-700 text-slate-400 text-xs font-medium hover:border-slate-500 hover:text-slate-300 transition-all"
          >
            New analysis
          </button>
        </div>
      </div>

      <div className="bg-slate-800/30 rounded-xl p-6 border border-slate-700/50">
        {formatAnalysis(analysis)}
      </div>

      <p className="text-slate-600 text-xs text-center">
        Generated by DashboardIntel · For internal use only · Not financial or legal advice
      </p>
    </div>
  );
}